spring:
    datasource:
        url: jdbc:mysql://localhost:3306/usersdb
        username: root
        password: abc123-
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
server:
    port: 8082
    servlet:
        context-path: /identity